const PLATFORMS = {
  VISA: 'visa',
  MASTERCARD: 'mastercard',
  PAYPAL: 'paypal',
  AMERICAN_EXPRESS: 'american',
  CARTES: 'cartes',
};

export const PAYMENT_MAP = {
  DEFAULT: [PLATFORMS.VISA, PLATFORMS.MASTERCARD, PLATFORMS.PAYPAL, PLATFORMS.AMERICAN_EXPRESS],
  ES: [PLATFORMS.VISA, PLATFORMS.MASTERCARD, PLATFORMS.PAYPAL, PLATFORMS.AMERICAN_EXPRESS],
  FR: [PLATFORMS.VISA, PLATFORMS.MASTERCARD, PLATFORMS.PAYPAL, PLATFORMS.AMERICAN_EXPRESS, PLATFORMS.CARTES],
  IT: [PLATFORMS.VISA, PLATFORMS.MASTERCARD, PLATFORMS.PAYPAL, PLATFORMS.AMERICAN_EXPRESS],
  UK: [PLATFORMS.VISA, PLATFORMS.MASTERCARD, PLATFORMS.PAYPAL, PLATFORMS.AMERICAN_EXPRESS],
};
